"""
Pydantic schemas for the TestDefinition entity.

Backend-internal schemas for this milestone only — not the frozen
cross-module TestDefinition contract (see app/models/test_definition.py
docstring and the milestone report's cross-module requirements section).

Step validation here intentionally mirrors the execution engine's minimal
step model (navigate/click/fill) so that a TestDefinition's `content`
stored via this API is guaranteed to be shaped the way the execution
engine expects — without duplicating execution *logic* (no browser
actions happen here, only shape/field validation).

Task 8: each step now optionally carries `id`, the stable step
identifier generated by Claude 3's Intelligence module. It is never
required (existing TestDefinitions created before Task 8 have none) and
never fabricated here — it is only accepted and preserved as-is.

Intelligence execution payload ingestion: `ExecutionPayloadCreate`
mirrors Intelligence's actual execution payload contract
(test_generation/execution_payload.py's to_execution_test_payload
output) exactly: {"journeyId": ..., "steps": [...]}. Steps reuse the
same Step union, extended with an optional `selectorKind` field (present
in Intelligence's payload, ignored by the execution engine, but
preserved verbatim in storage rather than silently dropped).
`source_step_id`/`source_event_id` are intentionally not part of this
schema, since they are not part of that payload contract.
"""

from datetime import datetime
from typing import Literal, Union

from pydantic import BaseModel, ConfigDict, Field, TypeAdapter


class NavigateStep(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str | None = Field(default=None, min_length=1)
    type: Literal["navigate"]
    url: str = Field(min_length=1)


class ClickStep(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str | None = Field(default=None, min_length=1)
    type: Literal["click"]
    selector: str = Field(min_length=1)
    # Intelligence's execution payload (test_generation/execution_payload.py)
    # may include "selectorKind" ("data-testid" / "id"). The Backend has no
    # use for it (execution-engine ignores it), but preserves it verbatim
    # in stored content rather than silently dropping it.
    selector_kind: str | None = Field(default=None, alias="selectorKind", min_length=1)


class FillStep(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str | None = Field(default=None, min_length=1)
    type: Literal["fill"]
    selector: str = Field(min_length=1)
    value: str = ""
    selector_kind: str | None = Field(default=None, alias="selectorKind", min_length=1)


Step = Union[NavigateStep, ClickStep, FillStep]

_StepListAdapter: TypeAdapter[list[Step]] = TypeAdapter(list[Step])


class TestDefinitionCreate(BaseModel):
    name: str = Field(min_length=1, max_length=255)
    description: str | None = Field(default=None, max_length=2000)
    content: list[Step] = Field(min_length=1)


class TestDefinitionRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    project_id: str
    name: str
    description: str | None
    content: list[dict]
    created_at: datetime


class ExecutionPayloadCreate(BaseModel):
    """
    Backend request schema mirroring Claude 3's Intelligence execution
    payload exactly, as produced by
    test_generation/execution_payload.py's to_execution_test_payload():

        {"journeyId": "...", "steps": [{"id": ..., "type": ..., ...}]}

    Steps reuse the exact same `Step` union/validation used by
    TestDefinitionCreate.content, so malformed step data (unknown step
    type, missing required fields, etc.) is rejected identically — no
    separate validation logic is introduced for this ingestion path.

    Deliberately does NOT include `source_step_id`/`source_event_id`:
    those are not part of Intelligence's execution payload contract
    (confirmed absent from to_execution_step_payload()'s output) and are
    intentionally not accepted or preserved here.
    """

    model_config = ConfigDict(populate_by_name=True)

    journey_id: str = Field(alias="journeyId", min_length=1)
    steps: list[Step] = Field(min_length=1)
